services:
  - type: web
    name: freshspace
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/services
    envVars:
      - key: BASE_URL
        value: https://freshspace.onrender.com